name: NameHighLighter
main: qc.maxx.namehighlighter.NameHighLighter
description: Make it clear when anyone mention your name in the chat!
author: Maxx_Qc
version: 1.1
commands:
  togglementionsound:
    description: Desactivate the sound whenever someone mention your name.
    aliases: [tms, togglems]
    usage: 'Use: /tms'
  nhreload:
    description: Reload the NameHighLighter plugin.
    usage: 'Use: /nhreload'
    permission: namehighlighter.reload
permissions:
  namehighlighter.*:
    default: op
    children:
      namehighlighter.reload: true
  namehighlighter.reload:
    default: op